### ISSUE TITLE
(feature) discussing pinging Hugging face API every 5 minutes

### ISSUE THREAD

**Issue by ChokunPlayZ** [Hobospider132/MahiruShiinaJS#1]
so there’s a different way to tackle this issue that I can come up with

the first one is using native JavaScript `setTimeout` function this does not require any external libraries and is the closest thing you can get to a `time.sleep` in python

the second way to do this is to use `node-corn` libary, this uses the traditional cornjob way of doing things, this is differential because it depends on the hosts clock so if the interval is 5 minutes it will run the code at 12.00, 12.05, 12.10, and so on, the setTimeout function will run the code once, wait `30000`ms then run it again

I can implement both because I actually use both type in my bot before I would personally go for `setTimeout` because it is a bit easier to implement because it’s a native JavaScript function it wouldn’t bloat the “node-modules” folder

**Comment by Hobospider132** [comment]
we can try the setTimeout feature for now, if it doesn't work i'll try the node-cron feature

**Comment by ChokunPlayZ** [comment]
You’ll have to add the code where it pings the API but in theory it should works when it is added, I’m going to left the other PR open for now

**Comment by Hobospider132** [comment]
the setTimeout feature didn't work, node-cron worked better
